//! Combat resolution calculator.
//!
//! Resolves an attack from an attacker unit against a defender unit,
//! applying special rules at the appropriate phases of the combat sequence.
//!
//! ## Combat Sequence & Rule Hook Points
//! 1. Attack count          - Impact(X)
//! 2. Hit roll setup        - Reliable, Artillery, Indirect, Thrust, Stealth
//! 3. Hit roll resolution   - Furious, Relentless, Surge, Rending
//! 4. Hit multiplication    - Blast(X)
//! 5. Defense roll setup    - AP(X)
//! 6. Defense roll resolve  - Bane, Unstoppable
//! 7. Wound application     - Deadly(X), Tough(X)
//! 8. Regeneration          - Regeneration (skipped by Bane/Rending/Unstoppable)

use crate::combat::context::CombatContext;
use crate::combat::dice;
use crate::models::rules::SpecialRule;
use crate::models::unit::Unit;
use crate::models::weapons::Weapon;

/// Detailed breakdown of a single attack resolution.
#[derive(Debug, Clone, Default)]
pub struct AttackResult {
    /// Name of the weapon that made the attack
    pub weapon_name: String,
    /// Base number of attacks rolled
    pub base_attacks: u32,
    /// Extra attacks generated by special rules (Furious, Surge, etc.)
    pub extra_attacks: u32,
    /// Hits scored before multiplication
    pub hits_before_multiplier: u32,
    /// Hits after Blast multiplication
    pub total_hits: u32,
    /// Hits blocked by the defender
    pub blocked_hits: u32,
    /// Wounds actually inflicted (after Deadly/Tough)
    pub wounds_inflicted: u32,
    /// Wounds ignored by Regeneration
    pub regenerated_wounds: u32,
    /// Net wounds after regeneration
    pub net_wounds: u32,
}

/// Overall result of resolving an attacker against a defender.
#[derive(Debug, Clone, Default)]
pub struct CombatResult {
    /// Per-weapon breakdowns
    pub attacks: Vec<AttackResult>,
    /// Total net wounds dealt to the defender
    pub total_net_wounds: u32,
    /// Total models removed from the defender
    pub models_removed: u32,
}

/// Resolve the attacks of `attacker` against `defender` under the given
/// combat context. This is the top-level entry point for the calculator.
///
/// # Errors
/// Returns an error string if the attack configuration is invalid.
pub fn resolve_attack(
    attacker: &Unit,
    defender: &Unit,
    context: &CombatContext,
) -> Result<CombatResult, String> {
    let mut result = CombatResult::default();

    let weapons: Vec<&Weapon> = if context.is_melee() {
        attacker.melee_weapons()
    } else {
        attacker.ranged_weapons()
    };

    for weapon in weapons {
        let attack = resolve_weapon_attack(attacker, weapon, defender, context)?;
        result.total_net_wounds = result
            .total_net_wounds
            .saturating_add(attack.net_wounds);
        result.attacks.push(attack);
    }

    result.models_removed = compute_models_removed(defender, result.total_net_wounds);

    Ok(result)
}

/// Resolve a single weapon's attacks against the defender.
fn resolve_weapon_attack(
    attacker: &Unit,
    weapon: &Weapon,
    defender: &Unit,
    context: &CombatContext,
) -> Result<AttackResult, String> {
    let mut attack = AttackResult {
        weapon_name: weapon.name.clone(),
        base_attacks: u32::from(weapon.total_attacks()),
        ..AttackResult::default()
    };

    // Phase 1: Attack count (Impact(X) would add dice here on a charge)
    // TODO: Resolve Impact(X)

    // Phase 2: Hit roll setup (modify Quality target)
    let hit_modifier = compute_hit_modifier(weapon, context);
    let quality_target = effective_quality(weapon, attacker, context);

    // Phase 3: Hit roll resolution
    let hit_rolls = dice::roll_d6s(attack.base_attacks, hit_modifier);
    let mut hits = dice::count_successes(&hit_rolls, quality_target);

    // Extra hits from Furious/Surge/Relentless on unmodified 6s
    let extra_hits = count_extra_hits(&hit_rolls, weapon, context);
    attack.extra_attacks = extra_hits;
    hits = hits.saturating_add(extra_hits);
    attack.hits_before_multiplier = hits;

    // Phase 4: Blast(X) hit multiplication
    let total_hits = apply_blast(hits, weapon, defender.quantity);
    attack.total_hits = total_hits;

    // Phase 5: Defense roll setup (AP modifies the defense target)
    let defense_target = effective_defense(weapon, defender, context);

    // Phase 6: Defense roll resolution
    let defense_rolls = dice::roll_d6s(total_hits, 0);
    let blocked = dice::count_successes(&defense_rolls, defense_target);
    attack.blocked_hits = blocked;

    let failed_blocks = total_hits.saturating_sub(blocked);

    // Phase 7: Wound application (Deadly(X) multiplies wounds)
    let wounds = apply_deadly(failed_blocks, weapon);
    attack.wounds_inflicted = wounds;

    // Phase 8: Regeneration (skipped if weapon ignores regen)
    let (net_wounds, regenerated) = apply_regeneration(wounds, defender, weapon);
    attack.regenerated_wounds = regenerated;
    attack.net_wounds = net_wounds;

    Ok(attack)
}

/// Compute the total modifier to apply to hit rolls.
/// Placeholder: currently only accounts for Indirect (moving penalty).
fn compute_hit_modifier(_weapon: &Weapon, context: &CombatContext) -> i32 {
    let mut modifier = 0i32;

    // Indirect: -1 to hit when shooting after moving
    // TODO: Check weapon rules for Indirect when attacker_moved

    // Artillery: +1 to hit vs >9", -2 when shot at from >9" (defender side)
    // TODO

    // Thrust: +1 to hit when charging (melee)
    // TODO

    // Stealth (defender): -1 to hit from >9"
    // TODO: needs attacker reference

    let _ = context;
    modifier
}

/// Determine the effective Quality target for hit rolls.
/// Reliable forces Quality 2+.
fn effective_quality(weapon: &Weapon, attacker: &Unit, context: &CombatContext) -> u8 {
    // Fatigued units only hit on unmodified 6
    if context.attacker_fatigued {
        return 6;
    }

    // Reliable: this weapon attacks at Quality 2+
    if weapon.special_rules.contains(&SpecialRule::Reliable) {
        return 2;
    }

    attacker.quality
}

/// Count extra hits generated by Furious/Surge/Relentless on unmodified 6s.
fn count_extra_hits(
    hit_rolls: &[dice::DieRoll],
    weapon: &Weapon,
    context: &CombatContext,
) -> u32 {
    let sixes = hit_rolls
        .iter()
        .filter(|r| r.is_unmodified_six())
        .count();

    let generates_extras = weapon
        .special_rules
        .iter()
        .any(|rule| rule_is_active_extra_hit(rule, context));

    if generates_extras {
        sixes.try_into().unwrap_or(u32::MAX)
    } else {
        0
    }
}

/// Whether an extra-hit-on-six rule is active given the combat context.
fn rule_is_active_extra_hit(rule: &SpecialRule, context: &CombatContext) -> bool {
    match rule {
        // Furious only triggers when charging in melee
        SpecialRule::Furious => context.is_charging && context.is_melee(),
        // Relentless only triggers at long range (ranged)
        SpecialRule::Relentless => context.is_ranged() && context.is_long_range(),
        // Surge triggers on any unmodified 6
        SpecialRule::Surge => true,
        _ => false,
    }
}

/// Apply Blast(X) multiplication, capped by the defender's model count.
fn apply_blast(hits: u32, weapon: &Weapon, defender_quantity: u8) -> u32 {
    let multiplier = weapon
        .special_rules
        .iter()
        .find_map(SpecialRule::blast_multiplier);

    match multiplier {
        Some(m) if m > 1 => {
            // Each hit is multiplied by X, but total capped by models in target
            let per_hit_cap = u32::from(m);
            let capped_multiplier = per_hit_cap.min(u32::from(defender_quantity));
            hits.saturating_mul(capped_multiplier)
        }
        _ => hits,
    }
}

/// Determine the effective Defense target, applying AP and cover.
fn effective_defense(weapon: &Weapon, defender: &Unit, context: &CombatContext) -> u8 {
    let mut defense = i32::from(defender.defense);

    // Cover: +1 Defense vs shooting
    if context.is_ranged() && context.defender_in_cover {
        defense = defense.saturating_add(1);
    }

    // AP(X): Target needs X higher to defend
    if let Some(ap) = weapon.get_ap() {
        defense = defense.saturating_add(i32::from(ap));
    }

    // Rending: unmodified 6 to hit gains AP(+4) — handled per-hit, placeholder
    // TODO: integrate Rending AP boost into the defense rolls for those hits

    // Clamp to valid range 2..=6 (a roll of 6 always succeeds regardless)
    defense.clamp(2, 6).try_into().unwrap_or(6)
}

/// Apply Deadly(X) wound multiplication.
fn apply_deadly(failed_blocks: u32, weapon: &Weapon) -> u32 {
    let multiplier = weapon
        .special_rules
        .iter()
        .find_map(SpecialRule::deadly_multiplier);

    match multiplier {
        Some(m) if m > 1 => failed_blocks.saturating_mul(u32::from(m)),
        _ => failed_blocks,
    }
}

/// Apply defender Regeneration. Returns (net_wounds, regenerated_count).
fn apply_regeneration(wounds: u32, defender: &Unit, weapon: &Weapon) -> (u32, u32) {
    // If the weapon ignores regeneration, skip entirely
    let ignores_regen = weapon
        .special_rules
        .iter()
        .any(SpecialRule::ignores_regeneration);

    if ignores_regen || !defender.has_regeneration() {
        return (wounds, 0);
    }

    // Regeneration: 5+ to ignore each wound
    let regen_rolls = dice::roll_d6s(wounds, 0);
    let ignored = dice::count_successes(&regen_rolls, 5);
    let net = wounds.saturating_sub(ignored);
    (net, ignored)
}

/// Compute how many models are removed given net wounds and tough values.
fn compute_models_removed(defender: &Unit, net_wounds: u32) -> u32 {
    let tough = defender.effective_tough();
    if tough == 0 {
        return 0;
    }
    net_wounds / u32::from(tough)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::combat::context::CombatContext;
    use crate::models::unit::Unit;
    use crate::models::weapons::Weapon;

    #[test]
    fn test_basic_ranged_attack_resolves() {
        let attacker = Unit::new("Shooter", 3, 3, 3)
            .with_weapon(Weapon::ranged("Rifle", 3, 1, 24));
        let defender = Unit::new("Target", 5, 3, 4);

        let context = CombatContext::ranged(12);
        let result = resolve_attack(&attacker, &defender, &context);
        assert!(result.is_ok());
    }

    #[test]
    fn test_ap_lowers_defense() {
        let defender = Unit::new("Target", 5, 3, 3);
        let weapon = Weapon::ranged("Plasma", 1, 1, 24).with_rule(SpecialRule::AP(1));
        let context = CombatContext::ranged(12);

        let effective = effective_defense(&weapon, &defender, &context);
        // Base defense 3, AP(1) raises required roll to 4
        assert_eq!(effective, 4);
    }

    #[test]
    fn test_blast_multiplies_hits() {
        let weapon = Weapon::ranged("Launcher", 1, 2, 24).with_rule(SpecialRule::Blast(3));
        // Defender has 2 models, so multiplier capped at 2
        let total = apply_blast(2, &weapon, 2);
        assert_eq!(total, 4);
    }

    #[test]
    fn test_deadly_multiplies_wounds() {
        let weapon = Weapon::melee("Claws", 1, 1).with_rule(SpecialRule::Deadly(2));
        assert_eq!(apply_deadly(3, &weapon), 6);
    }
}