//! YAML loader for army data files.
//!
//! This module provides functionality to load army data from YAML files
//! generated by the data-collector crate and convert them to the internal
//! model types used by the API.

use crate::models::rules::SpecialRule;
use crate::models::unit::Unit;
use crate::models::upgrades::{
    ReplaceCount, SelectionMode, UpgradeGroup, UpgradeOption, WeaponChange,
};
use crate::models::weapons::Weapon;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::Path;

/// Errors that can occur during YAML loading.
#[derive(Debug, thiserror::Error)]
pub enum YamlError {
    #[error("Failed to read YAML file: {0}")]
    Io(#[from] std::io::Error),

    #[error("Failed to parse YAML: {0}")]
    Parse(#[from] serde_yaml::Error),

    #[error("No army data found in YAML file")]
    NoArmyData,

    #[error("Invalid quality format: {0}")]
    InvalidQuality(String),

    #[error("Invalid defense format: {0}")]
    InvalidDefense(String),

    #[error("Invalid attacks format: {0}")]
    InvalidAttacks(String),

    #[error("Invalid range format: {0}")]
    InvalidRange(String),

    #[error("Invalid special rule: {0}")]
    InvalidSpecialRule(String),

    #[error("Invalid cost modifier: {0}")]
    InvalidCostModifier(String),
}

/// YAML representation of an army file: one or more version keys, each
/// mapping to an army roster. A `BTreeMap` makes iteration deterministic
/// so multi-version files always resolve the same version.
#[derive(Debug, Deserialize)]
pub struct YamlArmyFile {
    #[serde(flatten)]
    pub versions: BTreeMap<String, YamlArmy>,
}

/// YAML representation of an army.
#[derive(Debug, Deserialize)]
pub struct YamlArmy {
    pub name: String,
    pub id: String,
    pub units: Vec<YamlUnit>,
}

/// YAML representation of a unit.
#[derive(Debug, Deserialize)]
pub struct YamlUnit {
    pub name: String,
    pub size: u8,
    pub quality: String,
    pub defense: String,
    #[serde(default)]
    pub tough: Option<u8>,
    pub weapons: Vec<YamlWeapon>,
    #[serde(default)]
    pub special_rules: Vec<String>,
    pub cost: u16,
    #[serde(default)]
    pub upgrade_categories: Vec<YamlUpgradeCategory>,
}

/// YAML representation of a weapon.
#[derive(Debug, Deserialize)]
pub struct YamlWeapon {
    pub name: String,
    #[serde(default)]
    pub range: Option<String>,
    pub attacks: String,
    #[serde(default)]
    pub ap: Option<String>,
    #[serde(default)]
    pub special_rules: Vec<String>,
}

/// YAML representation of an upgrade category.
#[derive(Debug, Deserialize)]
pub struct YamlUpgradeCategory {
    pub category: String,
    pub upgrades: Vec<YamlUpgrade>,
}

/// YAML representation of an upgrade option.
#[derive(Debug, Deserialize)]
pub struct YamlUpgrade {
    pub name: String,
    #[serde(default)]
    pub rules: Option<String>,
    pub cost_modifier: String,
}

/// Load an army from a YAML file.
///
/// # Errors
///
/// Returns an error if the file cannot be read or parsed.
pub fn load_army_from_yaml(path: &Path) -> Result<(String, YamlArmy), YamlError> {
    let contents = std::fs::read_to_string(path)?;
    parse_army_yaml(&contents)
}

/// Parse army YAML text into (version, army).
///
/// When several version keys are present, the highest-sorting key is
/// selected so the result is deterministic.
///
/// # Errors
///
/// Returns an error if the YAML cannot be parsed or holds no army.
pub fn parse_army_yaml(contents: &str) -> Result<(String, YamlArmy), YamlError> {
    let yaml_file: YamlArmyFile = serde_yaml::from_str(contents)?;
    let (version, army) = yaml_file
        .versions
        .into_iter()
        .next_back()
        .ok_or(YamlError::NoArmyData)?;

    Ok((version, army))
}

/// Convert a YAML army to the internal Army model.
///
/// # Errors
///
/// Returns an error if any unit cannot be converted.
pub fn convert_army(yaml_army: &YamlArmy) -> Result<Vec<Unit>, YamlError> {
    yaml_army.units.iter().map(convert_unit).collect()
}

/// Convert a YAML unit to the internal Unit model.
///
/// # Errors
///
/// Returns an error if the unit cannot be converted.
pub fn convert_unit(yaml_unit: &YamlUnit) -> Result<Unit, YamlError> {
    let quality = parse_quality(&yaml_unit.quality)?;
    let defense = parse_defense(&yaml_unit.defense)?;

    let mut unit =
        Unit::new(&yaml_unit.name, yaml_unit.size, quality, defense).with_points(yaml_unit.cost);

    // Set tough value if present
    if let Some(tough) = yaml_unit.tough {
        unit.tough = tough;
    }

    // Convert weapons (unit size = number of models wielding them)
    for yaml_weapon in &yaml_unit.weapons {
        let weapon = convert_weapon(yaml_weapon, yaml_unit.size)?;
        unit = unit.with_weapon(weapon);
    }

    // Convert special rules
    for rule_str in &yaml_unit.special_rules {
        let rule = parse_special_rule(rule_str)?;
        unit = unit.with_rule(rule);
    }

    // Convert upgrade categories
    for yaml_category in &yaml_unit.upgrade_categories {
        let upgrade_group = convert_upgrade_category(yaml_category)?;
        unit = unit.with_upgrades(upgrade_group);
    }

    Ok(unit)
}

/// Convert a YAML weapon to the internal Weapon model.
///
/// # Errors
///
/// Returns an error if the weapon cannot be converted.
/// Convert a YAML weapon. `quantity` is the number of models wielding it
/// (the unit size; catalogs do not record per-weapon wielder counts).
///
/// # Errors
///
/// Returns an error if the weapon cannot be converted.
pub fn convert_weapon(yaml_weapon: &YamlWeapon, quantity: u8) -> Result<Weapon, YamlError> {
    let attacks = parse_attacks(&yaml_weapon.attacks)?;

    // Determine if this is a melee or ranged weapon
    let weapon = if let Some(range_str) = &yaml_weapon.range {
        let range = parse_range(range_str)?;
        Weapon::ranged(&yaml_weapon.name, quantity, attacks, range)
    } else {
        Weapon::melee(&yaml_weapon.name, quantity, attacks)
    };

    // Add AP if present
    let mut weapon = weapon;
    if let Some(ap_str) = &yaml_weapon.ap {
        let ap_rule = parse_ap(ap_str)?;
        weapon = weapon.with_rule(ap_rule);
    }

    // Add special rules
    for rule_str in &yaml_weapon.special_rules {
        let rule = parse_special_rule(rule_str)?;
        weapon = weapon.with_rule(rule);
    }

    Ok(weapon)
}

/// Convert a YAML upgrade category to the internal `UpgradeGroup` model.
///
/// # Errors
///
/// Returns an error if the category cannot be converted.
pub fn convert_upgrade_category(
    yaml_category: &YamlUpgradeCategory,
) -> Result<UpgradeGroup, YamlError> {
    let mode = determine_selection_mode(&yaml_category.category);

    let mut options = Vec::new();
    for yaml_upgrade in &yaml_category.upgrades {
        let option = convert_upgrade_option(yaml_upgrade)?;
        options.push(option);
    }

    Ok(UpgradeGroup {
        name: yaml_category.category.clone(),
        mode,
        options,
        target_weapon: target_weapon_from_category(&yaml_category.category),
        replace_count: replace_count_from_category(&yaml_category.category),
    })
}

/// The weapon a replacement category swaps out, parsed from the category
/// name. `Replace Twin Heavy Flamer` -> `Twin Heavy Flamer`;
/// `Replace Combat Shield and CCW` -> `Combat Shield and CCW`;
/// `Replace all Hunting Hounds` -> `Hunting Hounds`. `None` for
/// non-replacement categories.
fn target_weapon_from_category(category: &str) -> Option<String> {
    let rest = category.strip_prefix("Replace ")?;
    let rest = rest.strip_prefix("all ").unwrap_or(rest);
    let rest = rest.strip_prefix("any ").unwrap_or(rest);
    let rest = rest.strip_prefix("one ").unwrap_or(rest);
    (!rest.is_empty()).then(|| rest.to_string())
}

/// How many instances of the target a replacement removes: `Replace any X`
/// removes one instance, every other replacement removes all.
fn replace_count_from_category(category: &str) -> ReplaceCount {
    if category.starts_with("Replace any") {
        ReplaceCount::One
    } else {
        ReplaceCount::All
    }
}

/// Convert a YAML upgrade to the internal `UpgradeOption` model.
///
/// The `rules` string carries either weapon specifications (e.g.
/// `24", A6, AP(1)`) for replacement entries — converted into a
/// [`WeaponChange`] — or plain special rules (e.g. `Furious`) for rule-only
/// entries. Cost and description are always preserved.
///
/// # Errors
///
/// Returns an error if the cost modifier cannot be parsed.
pub fn convert_upgrade_option(yaml_upgrade: &YamlUpgrade) -> Result<UpgradeOption, YamlError> {
    let cost = parse_cost_modifier(&yaml_upgrade.cost_modifier)?;
    let description = yaml_upgrade
        .rules
        .clone()
        .unwrap_or_else(|| String::from("No additional rules"));

    let rules = yaml_upgrade.rules.as_deref().unwrap_or("");

    // Replacement entries use weapon-specification syntax: optional range,
    // one or more "A<attacks>" values, then rule names.
    if let Some(weapon) = parse_upgrade_weapon(rules) {
        return Ok(UpgradeOption {
            name: yaml_upgrade.name.clone(),
            description,
            cost,
            weapon_change: Some(WeaponChange::Replace(weapon)),
            add_rules: Vec::new(),
        });
    }

    // Otherwise the string lists special rules, possibly comma-separated.
    // Unparseable fragments are left in the description so they stay
    // visible without failing the whole load.
    let mut add_rules = Vec::new();
    for part in rules.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Ok(rule) = parse_special_rule(part) {
            add_rules.push(rule);
        }
    }

    Ok(UpgradeOption {
        name: yaml_upgrade.name.clone(),
        description,
        cost,
        weapon_change: None,
        add_rules,
    })
}

/// Parse an upgrade option's weapon specification, e.g.
/// `24", A6, AP(1)` -> a ranged weapon with 6 attacks and AP(1), or
/// `A2, Blast(3)` -> a melee weapon. Returns `None` when the string is not
/// in weapon-specification form (no `A<number>` attacks value).
fn parse_upgrade_weapon(rules: &str) -> Option<Weapon> {
    let parts: Vec<&str> = rules
        .split(',')
        .map(str::trim)
        .filter(|p| !p.is_empty())
        .collect();

    let mut attacks: Option<u8> = None;
    let mut range: Option<u8> = None;
    let mut rule_names: Vec<&str> = Vec::new();

    for part in &parts {
        if let Some(range_str) = part.strip_suffix('"')
            && let Ok(value) = range_str.parse::<u8>()
        {
            range = Some(value);
            continue;
        }
        if let Some(numeric) = part.strip_prefix('A')
            && let Ok(value) = numeric.parse::<u8>()
        {
            // Multiple attack values (e.g. "A6, ..., A4"): keep the strongest.
            attacks = attacks.map_or(Some(value), |current| Some(current.max(value)));
            continue;
        }
        rule_names.push(part);
    }

    let attacks = attacks?;
    if rule_names.iter().any(|r| !is_known_rule(r)) {
        // Unknown rule names: the string is descriptive text, not a clean
        // weapon specification; keep it as a description-only option.
        return None;
    }

    let mut weapon = range.map_or_else(
        || Weapon::melee("Weapon", 1, attacks),
        |r| Weapon::ranged("Weapon", 1, attacks, r),
    );
    for name in &rule_names {
        weapon = weapon.with_rule(parse_special_rule(name).ok()?);
    }
    Some(weapon)
}

/// Whether a fragment parses to a *named* special rule (as opposed to the
/// `Unmodelled` fallback used for free text). Used to classify upgrade
/// `rules` strings as weapon specifications vs. descriptive text.
fn is_known_rule(fragment: &str) -> bool {
    parse_special_rule(fragment)
        .is_ok_and(|rule| !matches!(rule, crate::models::rules::SpecialRule::Unmodelled(_)))
}

/// Parse a `3+`-style stat, enforcing the legal 2..=6 range so bad data
/// fails at load time instead of test time.
fn parse_stat(stat_str: &str) -> Option<u8> {
    let value: u8 = stat_str.trim_end_matches('+').parse().ok()?;
    (2..=6).contains(&value).then_some(value)
}

/// Parse a quality string like "3+" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format or value (2..=6) is invalid.
fn parse_quality(quality_str: &str) -> Result<u8, YamlError> {
    parse_stat(quality_str).ok_or_else(|| YamlError::InvalidQuality(quality_str.to_string()))
}

/// Parse a defense string like "3+" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format or value (2..=6) is invalid.
fn parse_defense(defense_str: &str) -> Result<u8, YamlError> {
    parse_stat(defense_str).ok_or_else(|| YamlError::InvalidDefense(defense_str.to_string()))
}

/// Parse an attacks string like "A4" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_attacks(attacks_str: &str) -> Result<u8, YamlError> {
    let trimmed = attacks_str.trim_start_matches('A');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidAttacks(attacks_str.to_string()))
}

/// Parse a range string like "18\"" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_range(range_str: &str) -> Result<u8, YamlError> {
    let trimmed = range_str.trim_end_matches('"');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidRange(range_str.to_string()))
}

/// Parse an AP string like "AP(1)" into a `SpecialRule`.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_ap(ap_str: &str) -> Result<SpecialRule, YamlError> {
    if ap_str == "AP" {
        return Ok(SpecialRule::AP(1));
    }

    let trimmed = ap_str.trim_start_matches("AP(").trim_end_matches(')');
    let value = trimmed
        .parse()
        .map_err(|_| YamlError::InvalidSpecialRule(ap_str.to_string()))?;
    Ok(SpecialRule::AP(value))
}

/// Parse a special rule string into a `SpecialRule` enum variant.
///
/// Catalogs use display-form names (`"Hive Bond"`, `"Self-Destruct(2)"`,
/// `"Versatile Attack"`) rather than the enum's CamelCase identifiers, so
/// the raw name is normalized to a lookup key before matching. Unknown
/// display rules are preserved verbatim in [`SpecialRule::Unmodelled`] so a
/// roster still round-trips faithfully; only blank rule strings fail.
///
/// # Errors
///
/// Returns an error only if the rule string is blank.
pub fn parse_special_rule(rule_str: &str) -> Result<SpecialRule, YamlError> {
    let (key, value) = parse_rule_parts(rule_str)
        .ok_or_else(|| YamlError::InvalidSpecialRule(rule_str.to_string()))?;

    // Spawn carries a named (non-numeric) payload; keep the inner string.
    if key == "spawn" {
        let payload = rule_str
            .split_once('(')
            .and_then(|(_, rest)| rest.rsplit_once(')'))
            .map_or_else(
                || rule_str.trim().to_string(),
                |(inner, _)| inner.trim().to_string(),
            );
        return Ok(SpecialRule::Spawn(payload));
    }

    Ok(match_rule(&key, value, rule_str.trim()))
}

/// Split `rule_str` into (normalized lookup key, optional numeric
/// parameter). `"Self-Destruct(2)"` -> `("selfdestruct", Some(2))`,
/// `"Caster Group"` -> `("castergroup", None)`. Non-numeric parameters
/// (e.g. `Spawn(Spores [5])`) yield `None`; the raw string is carried by
/// the caller when the key needs it. Returns `None` only for blank input.
fn parse_rule_parts(rule_str: &str) -> Option<(String, Option<u8>)> {
    // Catalog rule names use ASCII parentheses; split_once avoids byte
    // indexing, which would panic if a boundary fell inside a multi-byte
    // character.
    let (base, value) = match rule_str.split_once('(') {
        Some((before, rest)) => {
            let inner = rest.rsplit_once(')')?.0;
            (before.trim(), inner.trim().parse::<u8>().ok())
        }
        None => (rule_str.trim(), None),
    };
    let key = base.to_ascii_lowercase().replace([' ', '-', '.', '&'], "");
    if key.is_empty() {
        None
    } else {
        Some((key, value))
    }
}

/// Resolve a normalized rule key to a [`SpecialRule`]. Parameterized
/// families take a value (defaulting when the display name omitted it,
/// e.g. bare `"AP"` -> `AP(1)`); everything else is matched as a flag
/// rule, and unknown keys fall back to [`SpecialRule::Unmodelled`]
/// carrying the original display string.
fn match_rule(key: &str, value: Option<u8>, display: &str) -> SpecialRule {
    // Parameterized families (value defaults when the display name is bare).
    match key {
        "ap" => SpecialRule::AP(value.unwrap_or(1)),
        "blast" => SpecialRule::Blast(value.unwrap_or(1)),
        "deadly" => SpecialRule::Deadly(value.unwrap_or(1)),
        "fear" => SpecialRule::Fear(value.unwrap_or(1)),
        "impact" => SpecialRule::Impact(value.unwrap_or(1)),
        "tough" => SpecialRule::Tough(value.unwrap_or(1)),
        "caster" => SpecialRule::Caster(value.unwrap_or(1)),
        "transport" => SpecialRule::Transport(value.unwrap_or(1)),
        "ravage" => SpecialRule::Ravage(value.unwrap_or(1)),
        "piercingtag" => SpecialRule::PiercingTag(value.unwrap_or(1)),
        "retaliate" => SpecialRule::Retaliate(value.unwrap_or(1)),
        "selfdestruct" => SpecialRule::SelfDestruct(value.unwrap_or(1)),
        "surpriseattack" => SpecialRule::SurpriseAttack(value.unwrap_or(1)),
        "deathstrike" => SpecialRule::Deathstrike(value.unwrap_or(3)),
        "heavyimpact" => SpecialRule::HeavyImpact(value.unwrap_or(3)),
        "crossingattack" => SpecialRule::CrossingAttack(value.unwrap_or(1)),
        _ => match_flag_rule(key, display),
    }
}

/// Flag (parameterless) rule lookup backing [`match_rule`]. The table is
/// generated from the `SpecialRule` enum (one arm per unit variant); unknown
/// keys fall back to [`SpecialRule::Unmodelled`] so rosters round-trip.
#[allow(clippy::too_many_lines)] // generated lookup table: one arm per variant
fn match_flag_rule(key: &str, display: &str) -> SpecialRule {
    match key {
        "agile" => SpecialRule::Agile,
        "aircraft" => SpecialRule::Aircraft,
        "ambush" => SpecialRule::Ambush,
        "ambushingpiercingshot" => SpecialRule::AmbushingPiercingShot,
        "artillery" => SpecialRule::Artillery,
        "badshot" => SpecialRule::BadShot,
        "bane" => SpecialRule::Bane,
        "battleborn" => SpecialRule::Battleborn,
        "bloodborn" => SpecialRule::Bloodborn,
        "bounding" => SpecialRule::Bounding,
        "breathattack" => SpecialRule::BreathAttack,
        "brutalfighter" => SpecialRule::BrutalFighter,
        "castergroup" => SpecialRule::CasterGroup,
        "castingdebuff" => SpecialRule::CastingDebuff,
        "changebound" => SpecialRule::Changebound,
        "clanwarrior" => SpecialRule::ClanWarrior,
        "counter" => SpecialRule::Counter,
        "counterattack" => SpecialRule::CounterAttack,
        "couragebuff" => SpecialRule::CourageBuff,
        "crack" => SpecialRule::Crack,
        "darkborn" => SpecialRule::Darkborn,
        "destructive" => SpecialRule::Destructive,
        "devout" => SpecialRule::Devout,
        "devoutboost" => SpecialRule::DevoutBoost,
        "disintegrate" => SpecialRule::Disintegrate,
        "evasive" => SpecialRule::Evasive,
        "fanatic" => SpecialRule::Fanatic,
        "fast" => SpecialRule::Fast,
        "fearless" => SpecialRule::Fearless,
        "ferocious" => SpecialRule::Ferocious,
        "ferociousboost" => SpecialRule::FerociousBoost,
        "flying" => SpecialRule::Flying,
        "fortified" => SpecialRule::Fortified,
        "furious" => SpecialRule::Furious,
        "furiousaura" => SpecialRule::FuriousAura,
        "furiousbuff" => SpecialRule::FuriousBuff,
        "goodshot" => SpecialRule::GoodShot,
        "groundedstealth" => SpecialRule::GroundedStealth,
        "guardedbuff" => SpecialRule::GuardedBuff,
        "guardian" => SpecialRule::Guardian,
        "guerrilla" => SpecialRule::Guerrilla,
        "harassing" => SpecialRule::Harassing,
        "havocbound" => SpecialRule::Havocbound,
        "hazardous" => SpecialRule::Hazardous,
        "hero" => SpecialRule::Hero,
        "highborn" => SpecialRule::Highborn,
        "hitandrunfighter" | "hitrun" => SpecialRule::HitAndRunFighter,
        "hivebond" => SpecialRule::HiveBond,
        "hivebondboost" => SpecialRule::HiveBondBoost,
        "hivebondboostaura" => SpecialRule::HiveBondBoostAura,
        "holdtheline" => SpecialRule::HoldTheLine,
        "honorcode" => SpecialRule::HonorCode,
        "immobile" => SpecialRule::Immobile,
        "increasedshootingrange" => SpecialRule::IncreasedShootingRange,
        "increasedshootingrangeaura" => SpecialRule::IncreasedShootingRangeAura,
        "indirect" => SpecialRule::Indirect,
        "infected" => SpecialRule::Infected,
        "infiltrate" => SpecialRule::Infiltrate,
        "inquisitorialagent" => SpecialRule::InquisitorialAgent,
        "knightborn" => SpecialRule::Knightborn,
        "lacerate" => SpecialRule::Lacerate,
        "limited" => SpecialRule::Limited,
        "lustbound" => SpecialRule::Lustbound,
        "machinefog" => SpecialRule::MachineFog,
        "martialprowess" => SpecialRule::MartialProwess,
        "meleeevasion" => SpecialRule::MeleeEvasion,
        "meleeslayer" => SpecialRule::MeleeSlayer,
        "mischievous" => SpecialRule::Mischievous,
        "mobileartillery" => SpecialRule::MobileArtillery,
        "noretreat" => SpecialRule::NoRetreat,
        "piercingassault" => SpecialRule::PiercingAssault,
        "piercinggrowth" => SpecialRule::PiercingGrowth,
        "plaguebound" => SpecialRule::Plaguebound,
        "pointblanksurge" => SpecialRule::PointBlankSurge,
        "precise" => SpecialRule::Precise,
        "precisiondebuff" => SpecialRule::PrecisionDebuff,
        "precisionfighterbuff" => SpecialRule::PrecisionFighterBuff,
        "predatorfighter" => SpecialRule::PredatorFighter,
        "primal" => SpecialRule::Primal,
        "primalboostbuff" => SpecialRule::PrimalBoostBuff,
        "primeborn" => SpecialRule::Primeborn,
        "protected" => SpecialRule::Protected,
        "quickreadjustment" => SpecialRule::QuickReadjustment,
        "rapidambush" => SpecialRule::RapidAmbush,
        "rapidblink" => SpecialRule::RapidBlink,
        "rapidcharge" => SpecialRule::RapidCharge,
        "rapidchargeaura" => SpecialRule::RapidChargeAura,
        "regeneration" => SpecialRule::Regeneration,
        "regenerationaura" => SpecialRule::RegenerationAura,
        "regenerativestrength" => SpecialRule::RegenerativeStrength,
        "relentless" => SpecialRule::Relentless,
        "reliable" => SpecialRule::Reliable,
        "rending" => SpecialRule::Rending,
        "resistance" => SpecialRule::Resistance,
        "scout" => SpecialRule::Scout,
        "scrapper" => SpecialRule::Scrapper,
        "scurry" => SpecialRule::Scurry,
        "selfrepair" => SpecialRule::SelfRepair,
        "selfrepairboostbuff" => SpecialRule::SelfRepairBoostBuff,
        "shatter" => SpecialRule::Shatter,
        "shielded" => SpecialRule::Shielded,
        "shred" => SpecialRule::Shred,
        "slow" => SpecialRule::Slow,
        "spellconduit" => SpecialRule::SpellConduit,
        "stealth" => SpecialRule::Stealth,
        "stealthbuff" => SpecialRule::StealthBuff,
        "strafing" => SpecialRule::Strafing,
        "strider" => SpecialRule::Strider,
        "sturdy" => SpecialRule::Sturdy,
        "surge" => SpecialRule::Surge,
        "swiftbuff" => SpecialRule::SwiftBuff,
        "takedown" => SpecialRule::Takedown,
        "takedownshot" => SpecialRule::TakedownShot,
        "takedownstrike" => SpecialRule::TakedownStrike,
        "targetingvisor" => SpecialRule::TargetingVisor,
        "tear" => SpecialRule::Tear,
        "teleport" => SpecialRule::Teleport,
        "thrust" => SpecialRule::Thrust,
        "unique" => SpecialRule::Unique,
        "unpredictable" => SpecialRule::Unpredictable,
        "unpredictablefighter" => SpecialRule::UnpredictableFighter,
        "unpredictablefightermark" => SpecialRule::UnpredictableFighterMark,
        "unpredictableshooter" => SpecialRule::UnpredictableShooter,
        "unstoppable" => SpecialRule::Unstoppable,
        "versatileattack" => SpecialRule::VersatileAttack,
        "warbound" => SpecialRule::Warbound,
        "watchborn" => SpecialRule::Watchborn,
        "wolfborn" => SpecialRule::Wolfborn,
        _ => SpecialRule::Unmodelled(display.to_string()),
    }
}

/// Determine the selection mode based on the category name.
fn determine_selection_mode(category: &str) -> SelectionMode {
    if category.contains("Replace") || category.contains("Upgrade with one") {
        SelectionMode::PickOne
    } else {
        SelectionMode::Multiple
    }
}

/// Parse a cost modifier string like "+5pts" or "Free" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_cost_modifier(cost_str: &str) -> Result<u16, YamlError> {
    // Handle "Free" as 0 cost
    if cost_str == "Free" {
        return Ok(0);
    }

    // Costs are additive; a negative modifier is not representable as u16.
    if cost_str.starts_with('-') {
        return Err(YamlError::InvalidCostModifier(cost_str.to_string()));
    }

    let trimmed = cost_str.trim_start_matches('+').trim_end_matches("pts");
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidCostModifier(cost_str.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_quality() {
        assert_eq!(parse_quality("3+").unwrap(), 3);
        assert_eq!(parse_quality("4+").unwrap(), 4);
        assert_eq!(parse_quality("2+").unwrap(), 2);
    }

    #[test]
    fn test_parse_attacks() {
        assert_eq!(parse_attacks("A4").unwrap(), 4);
        assert_eq!(parse_attacks("A1").unwrap(), 1);
        assert_eq!(parse_attacks("A6").unwrap(), 6);
    }

    #[test]
    fn test_parse_special_rule() {
        assert_eq!(parse_special_rule("AP(1)").unwrap(), SpecialRule::AP(1));
        assert_eq!(
            parse_special_rule("Blast(3)").unwrap(),
            SpecialRule::Blast(3)
        );
        assert_eq!(
            parse_special_rule("Fearless").unwrap(),
            SpecialRule::Fearless
        );
        assert_eq!(parse_special_rule("Hero").unwrap(), SpecialRule::Hero);
    }

    #[test]
    fn test_parse_display_name_rules() {
        // Display-form catalog names must map to named variants.
        assert_eq!(
            parse_special_rule("Hive Bond").unwrap(),
            SpecialRule::HiveBond
        );
        assert_eq!(
            parse_special_rule("Self-Destruct(2)").unwrap(),
            SpecialRule::SelfDestruct(2)
        );
        assert_eq!(
            parse_special_rule("Versatile Attack").unwrap(),
            SpecialRule::VersatileAttack
        );
        assert_eq!(
            parse_special_rule("Knightborn").unwrap(),
            SpecialRule::Knightborn
        );
        assert_eq!(
            parse_special_rule("Watchborn").unwrap(),
            SpecialRule::Watchborn
        );
        assert_eq!(
            parse_special_rule("Caster Group").unwrap(),
            SpecialRule::CasterGroup
        );
        assert_eq!(
            parse_special_rule("Machine-Fog").unwrap(),
            SpecialRule::MachineFog
        );
        assert_eq!(
            parse_special_rule("No Retreat").unwrap(),
            SpecialRule::NoRetreat
        );
        assert_eq!(
            parse_special_rule("Spawn(Spores [5])").unwrap(),
            SpecialRule::Spawn("Spores [5]".to_string())
        );
        // Bare AP defaults to AP(1)
        assert_eq!(parse_special_rule("AP").unwrap(), SpecialRule::AP(1));
    }

    #[test]
    fn test_parse_special_rule_blank_is_error() {
        assert!(parse_special_rule("   ").is_err());
    }

    #[test]
    fn test_parse_stat_range_rejects_out_of_bounds() {
        assert_eq!(parse_stat("3+"), Some(3));
        assert_eq!(parse_stat("2"), Some(2));
        assert_eq!(parse_stat("6+"), Some(6));
        assert_eq!(parse_stat("1+"), None);
        assert_eq!(parse_stat("7+"), None);
        assert_eq!(parse_stat("0"), None);
        assert_eq!(parse_stat("250"), None);
        assert_eq!(parse_stat("garbage"), None);
    }

    #[test]
    fn test_parse_range_reports_invalid_range() {
        let err = parse_range("not-a-range").unwrap_err();
        assert!(matches!(err, YamlError::InvalidRange(_)));
        let msg = err.to_string();
        assert!(msg.contains("Invalid range"), "unexpected message: {msg}");
    }

    #[test]
    fn test_version_selection_prefers_highest_key() {
        let yaml = "\n\
v2.0.0:
  name: Old
  id: old
  units: []
v3.5.3:
  name: New
  id: new
  units: []
\n";
        let (version, army) = parse_army_yaml(yaml).unwrap();
        assert_eq!(version, "v3.5.3");
        assert_eq!(army.name, "New");
    }

    #[test]
    fn test_version_single_entry_loads() {
        let yaml = "\n\
v3.5.3:
  name: Battle Brothers
  id: 78qp9l5
  units: []
\n";
        let (version, army) = parse_army_yaml(yaml).unwrap();
        assert_eq!(version, "v3.5.3");
        assert_eq!(army.id, "78qp9l5");
    }

    #[test]
    fn test_negative_cost_modifier_rejected() {
        assert!(matches!(
            parse_cost_modifier("-5pts"),
            Err(YamlError::InvalidCostModifier(_))
        ));
        assert_eq!(parse_cost_modifier("+5pts").unwrap(), 5);
        assert_eq!(parse_cost_modifier("Free").unwrap(), 0);
    }

    #[test]
    fn test_convert_weapon_uses_unit_quantity() {
        let w = YamlWeapon {
            name: "CCW".to_string(),
            range: None,
            attacks: "A2".to_string(),
            ap: None,
            special_rules: Vec::new(),
        };
        let weapon = convert_weapon(&w, 5).unwrap();
        assert_eq!(weapon.quantity, 5);
        assert_eq!(weapon.attacks, 2);
        assert_eq!(weapon.total_attacks(), 10);
        assert!(weapon.is_melee());

        let ranged = YamlWeapon {
            name: "Storm Rifle".to_string(),
            range: Some("24\"".to_string()),
            attacks: "A1".to_string(),
            ap: Some("AP(1)".to_string()),
            special_rules: Vec::new(),
        };
        let weapon = convert_weapon(&ranged, 3).unwrap();
        assert_eq!(weapon.quantity, 3);
        assert_eq!(weapon.range, Some(24));
        assert!(weapon.get_ap() == Some(1));
    }

    #[test]
    fn test_target_weapon_from_category() {
        assert_eq!(
            target_weapon_from_category("Replace CCW").as_deref(),
            Some("CCW")
        );
        assert_eq!(
            target_weapon_from_category("Replace Combat Shield and CCW").as_deref(),
            Some("Combat Shield and CCW")
        );
        assert_eq!(
            target_weapon_from_category("Replace all Hunting Hounds").as_deref(),
            Some("Hunting Hounds")
        );
        assert_eq!(
            target_weapon_from_category("Replace any CCW").as_deref(),
            Some("CCW")
        );
        assert_eq!(
            target_weapon_from_category("Replace one Heavy Pistol and CCW").as_deref(),
            Some("Heavy Pistol and CCW")
        );
        assert_eq!(
            target_weapon_from_category("Upgrade with one").as_deref(),
            None
        );
    }

    #[test]
    fn test_replace_count_from_category() {
        assert_eq!(
            replace_count_from_category("Replace any CCW"),
            ReplaceCount::One
        );
        assert_eq!(
            replace_count_from_category("Replace CCW"),
            ReplaceCount::All
        );
        assert_eq!(
            replace_count_from_category("Replace all Heavy Pistols and CCWs"),
            ReplaceCount::All
        );
        assert_eq!(
            replace_count_from_category("Upgrade with one"),
            ReplaceCount::All
        );
    }

    #[test]
    fn test_parse_upgrade_weapon_spec() {
        let w = parse_upgrade_weapon(r#"24", A6, AP(1)"#).unwrap();
        assert_eq!(w.range, Some(24));
        assert_eq!(w.attacks, 6);
        assert_eq!(w.get_ap(), Some(1));

        let w = parse_upgrade_weapon("A2, Blast(3)").unwrap();
        assert_eq!(w.range, None);
        assert_eq!(w.attacks, 2);
        assert!(matches!(
            w.special_rules.first(),
            Some(SpecialRule::Blast(3))
        ));

        // Plain rule text is not a weapon specification.
        assert!(parse_upgrade_weapon("Furious").is_none());
        assert!(parse_upgrade_weapon("").is_none());
    }

    #[test]
    fn test_convert_upgrade_option_preserves_rules_and_weapon() {
        // Rule-only entry
        let up = YamlUpgrade {
            name: "Jetpack".to_string(),
            rules: Some("Ambush, Flying".to_string()),
            cost_modifier: "+20pts".to_string(),
        };
        let option = convert_upgrade_option(&up).unwrap();
        assert_eq!(option.cost, 20);
        assert!(
            option
                .add_rules
                .contains(&crate::models::rules::SpecialRule::Ambush)
        );
        assert!(
            option
                .add_rules
                .contains(&crate::models::rules::SpecialRule::Flying)
        );
        assert!(option.weapon_change.is_none());

        // Weapon replacement entry
        let up = YamlUpgrade {
            name: "Rapid Storm Rifle, CCW".to_string(),
            rules: Some("24\", A6, AP(1)".to_string()),
            cost_modifier: "+70pts".to_string(),
        };
        let option = convert_upgrade_option(&up).unwrap();
        assert_eq!(option.cost, 70);
        assert!(matches!(
            option.weapon_change,
            Some(WeaponChange::Replace(_))
        ));
    }
}
