//! YAML loader for army data files.
//!
//! This module provides functionality to load army data from YAML files
//! generated by the data-collector crate and convert them to the internal
//! model types used by the API.

use crate::models::rules::SpecialRule;
use crate::models::unit::Unit;
use crate::models::upgrades::{ReplaceCount, SelectionMode, UpgradeGroup, UpgradeOption};
use crate::models::weapons::Weapon;
use serde::Deserialize;
use std::path::Path;

/// Errors that can occur during YAML loading.
#[derive(Debug, thiserror::Error)]
pub enum YamlError {
    #[error("Failed to read YAML file: {0}")]
    Io(#[from] std::io::Error),

    #[error("Failed to parse YAML: {0}")]
    Parse(#[from] serde_yaml::Error),

    #[error("No army data found in YAML file")]
    NoArmyData,

    #[error("Invalid quality format: {0}")]
    InvalidQuality(String),

    #[error("Invalid defense format: {0}")]
    InvalidDefense(String),

    #[error("Invalid attacks format: {0}")]
    InvalidAttacks(String),

    #[error("Invalid special rule: {0}")]
    InvalidSpecialRule(String),

    #[error("Invalid cost modifier: {0}")]
    InvalidCostModifier(String),
}

/// YAML representation of an army file.
#[derive(Debug, Deserialize)]
pub struct YamlArmyFile {
    #[serde(flatten)]
    pub versions: std::collections::HashMap<String, YamlArmy>,
}

/// YAML representation of an army.
#[derive(Debug, Deserialize)]
pub struct YamlArmy {
    pub name: String,
    pub id: String,
    pub units: Vec<YamlUnit>,
}

/// YAML representation of a unit.
#[derive(Debug, Deserialize)]
pub struct YamlUnit {
    pub name: String,
    pub size: u8,
    pub quality: String,
    pub defense: String,
    #[serde(default)]
    pub tough: Option<u8>,
    pub weapons: Vec<YamlWeapon>,
    #[serde(default)]
    pub special_rules: Vec<String>,
    pub cost: u16,
    #[serde(default)]
    pub upgrade_categories: Vec<YamlUpgradeCategory>,
}

/// YAML representation of a weapon.
#[derive(Debug, Deserialize)]
pub struct YamlWeapon {
    pub name: String,
    #[serde(default)]
    pub range: Option<String>,
    pub attacks: String,
    #[serde(default)]
    pub ap: Option<String>,
    #[serde(default)]
    pub special_rules: Vec<String>,
}

/// YAML representation of an upgrade category.
#[derive(Debug, Deserialize)]
pub struct YamlUpgradeCategory {
    pub category: String,
    pub upgrades: Vec<YamlUpgrade>,
}

/// YAML representation of an upgrade option.
#[derive(Debug, Deserialize)]
pub struct YamlUpgrade {
    pub name: String,
    #[serde(default)]
    pub rules: Option<String>,
    pub cost_modifier: String,
}

/// Load an army from a YAML file.
///
/// # Errors
///
/// Returns an error if the file cannot be read or parsed.
pub fn load_army_from_yaml(path: &Path) -> Result<(String, YamlArmy), YamlError> {
    let contents = std::fs::read_to_string(path)?;
    let yaml_file: YamlArmyFile = serde_yaml::from_str(&contents)?;

    // Get the first (and typically only) version
    let (version, army) = yaml_file
        .versions
        .into_iter()
        .next()
        .ok_or(YamlError::NoArmyData)?;

    Ok((version, army))
}

/// Convert a YAML army to the internal Army model.
///
/// # Errors
///
/// Returns an error if any unit cannot be converted.
pub fn convert_army(yaml_army: &YamlArmy) -> Result<Vec<Unit>, YamlError> {
    yaml_army.units.iter().map(convert_unit).collect()
}

/// Convert a YAML unit to the internal Unit model.
///
/// # Errors
///
/// Returns an error if the unit cannot be converted.
pub fn convert_unit(yaml_unit: &YamlUnit) -> Result<Unit, YamlError> {
    let quality = parse_quality(&yaml_unit.quality)?;
    let defense = parse_defense(&yaml_unit.defense)?;

    let mut unit =
        Unit::new(&yaml_unit.name, yaml_unit.size, quality, defense).with_points(yaml_unit.cost);

    // Set tough value if present
    if let Some(tough) = yaml_unit.tough {
        unit.tough = tough;
    }

    // Convert weapons
    for yaml_weapon in &yaml_unit.weapons {
        let weapon = convert_weapon(yaml_weapon)?;
        unit = unit.with_weapon(weapon);
    }

    // Convert special rules
    for rule_str in &yaml_unit.special_rules {
        let rule = parse_special_rule(rule_str)?;
        unit = unit.with_rule(rule);
    }

    // Convert upgrade categories
    for yaml_category in &yaml_unit.upgrade_categories {
        let upgrade_group = convert_upgrade_category(yaml_category)?;
        unit = unit.with_upgrades(upgrade_group);
    }

    Ok(unit)
}

/// Convert a YAML weapon to the internal Weapon model.
///
/// # Errors
///
/// Returns an error if the weapon cannot be converted.
pub fn convert_weapon(yaml_weapon: &YamlWeapon) -> Result<Weapon, YamlError> {
    let attacks = parse_attacks(&yaml_weapon.attacks)?;

    // Determine if this is a melee or ranged weapon
    let weapon = if let Some(range_str) = &yaml_weapon.range {
        let range = parse_range(range_str)?;
        Weapon::ranged(&yaml_weapon.name, 1, attacks, range)
    } else {
        Weapon::melee(&yaml_weapon.name, 1, attacks)
    };

    // Add AP if present
    let mut weapon = weapon;
    if let Some(ap_str) = &yaml_weapon.ap {
        let ap_rule = parse_ap(ap_str)?;
        weapon = weapon.with_rule(ap_rule);
    }

    // Add special rules
    for rule_str in &yaml_weapon.special_rules {
        let rule = parse_special_rule(rule_str)?;
        weapon = weapon.with_rule(rule);
    }

    Ok(weapon)
}

/// Convert a YAML upgrade category to the internal `UpgradeGroup` model.
///
/// # Errors
///
/// Returns an error if the category cannot be converted.
pub fn convert_upgrade_category(
    yaml_category: &YamlUpgradeCategory,
) -> Result<UpgradeGroup, YamlError> {
    let mode = determine_selection_mode(&yaml_category.category);

    let mut options = Vec::new();
    for yaml_upgrade in &yaml_category.upgrades {
        let option = convert_upgrade_option(yaml_upgrade)?;
        options.push(option);
    }

    Ok(UpgradeGroup {
        name: yaml_category.category.clone(),
        mode,
        options,
        target_weapon: None,
        replace_count: ReplaceCount::All,
    })
}

/// Convert a YAML upgrade to the internal `UpgradeOption` model.
///
/// # Errors
///
/// Returns an error if the upgrade cannot be converted.
pub fn convert_upgrade_option(yaml_upgrade: &YamlUpgrade) -> Result<UpgradeOption, YamlError> {
    let cost = parse_cost_modifier(&yaml_upgrade.cost_modifier)?;

    // For now, treat all upgrades as rule-only options
    // TODO: Implement weapon replacement/addition logic
    let description = yaml_upgrade
        .rules
        .clone()
        .unwrap_or_else(|| String::from("No additional rules"));

    Ok(UpgradeOption::rule(
        &yaml_upgrade.name,
        &description,
        cost,
        Vec::new(), // TODO: Parse rules into SpecialRule objects
    ))
}

/// Parse a quality string like "3+" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_quality(quality_str: &str) -> Result<u8, YamlError> {
    let trimmed = quality_str.trim_end_matches('+');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidQuality(quality_str.to_string()))
}

/// Parse a defense string like "3+" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_defense(defense_str: &str) -> Result<u8, YamlError> {
    let trimmed = defense_str.trim_end_matches('+');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidDefense(defense_str.to_string()))
}

/// Parse an attacks string like "A4" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_attacks(attacks_str: &str) -> Result<u8, YamlError> {
    let trimmed = attacks_str.trim_start_matches('A');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidAttacks(attacks_str.to_string()))
}

/// Parse a range string like "18\"" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_range(range_str: &str) -> Result<u8, YamlError> {
    let trimmed = range_str.trim_end_matches('"');
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidQuality(range_str.to_string()))
}

/// Parse an AP string like "AP(1)" into a `SpecialRule`.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_ap(ap_str: &str) -> Result<SpecialRule, YamlError> {
    if ap_str == "AP" {
        return Ok(SpecialRule::AP(1));
    }

    let trimmed = ap_str.trim_start_matches("AP(").trim_end_matches(')');
    let value = trimmed
        .parse()
        .map_err(|_| YamlError::InvalidSpecialRule(ap_str.to_string()))?;
    Ok(SpecialRule::AP(value))
}

/// Parse a special rule string into a `SpecialRule` enum variant.
///
/// # Errors
///
/// Returns an error if the rule cannot be parsed.
pub fn parse_special_rule(rule_str: &str) -> Result<SpecialRule, YamlError> {
    // Handle parameterized rules
    if let Some(value) = extract_parameter(rule_str, "AP") {
        return Ok(SpecialRule::AP(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Blast") {
        return Ok(SpecialRule::Blast(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Deadly") {
        return Ok(SpecialRule::Deadly(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Fear") {
        return Ok(SpecialRule::Fear(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Impact") {
        return Ok(SpecialRule::Impact(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Tough") {
        return Ok(SpecialRule::Tough(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Caster") {
        return Ok(SpecialRule::Caster(value));
    }
    if let Some(value) = extract_parameter(rule_str, "Transport") {
        return Ok(SpecialRule::Transport(value));
    }

    // Handle simple flag rules
    match rule_str {
        "Bane" => Ok(SpecialRule::Bane),
        "Battleborn" => Ok(SpecialRule::Battleborn),
        "Counter" => Ok(SpecialRule::Counter),
        "Fast" => Ok(SpecialRule::Fast),
        "Fearless" => Ok(SpecialRule::Fearless),
        "Flying" => Ok(SpecialRule::Flying),
        "Furious" => Ok(SpecialRule::Furious),
        "Immobile" => Ok(SpecialRule::Immobile),
        "Indirect" => Ok(SpecialRule::Indirect),
        "Limited" => Ok(SpecialRule::Limited),
        "Regeneration" => Ok(SpecialRule::Regeneration),
        "Relentless" => Ok(SpecialRule::Relentless),
        "Reliable" => Ok(SpecialRule::Reliable),
        "Rending" => Ok(SpecialRule::Rending),
        "Scout" => Ok(SpecialRule::Scout),
        "Shielded" => Ok(SpecialRule::Shielded),
        "Slow" => Ok(SpecialRule::Slow),
        "Stealth" => Ok(SpecialRule::Stealth),
        "Strider" => Ok(SpecialRule::Strider),
        "Surge" => Ok(SpecialRule::Surge),
        "Takedown" => Ok(SpecialRule::Takedown),
        "Thrust" => Ok(SpecialRule::Thrust),
        "Unstoppable" => Ok(SpecialRule::Unstoppable),
        "VersatileAttack" | "Versatile Attack" => Ok(SpecialRule::VersatileAttack),
        "Aircraft" => Ok(SpecialRule::Aircraft),
        "Ambush" => Ok(SpecialRule::Ambush),
        "Artillery" => Ok(SpecialRule::Artillery),
        "Hero" => Ok(SpecialRule::Hero),
        "HiveBond" => Ok(SpecialRule::HiveBond),
        "BreathAttack" => Ok(SpecialRule::BreathAttack),
        "CasterGroup" => Ok(SpecialRule::CasterGroup),
        "Destructive" => Ok(SpecialRule::Destructive),
        "Fortified" => Ok(SpecialRule::Fortified),
        "FuriousBuff" => Ok(SpecialRule::FuriousBuff),
        "HitAndRunFighter" => Ok(SpecialRule::HitAndRunFighter),
        "HiveBondBoost" => Ok(SpecialRule::HiveBondBoost),
        "IncreasedShootingRange" => Ok(SpecialRule::IncreasedShootingRange),
        "Infiltrate" => Ok(SpecialRule::Infiltrate),
        "NoRetreat" => Ok(SpecialRule::NoRetreat),
        "PiercingGrowth" => Ok(SpecialRule::PiercingGrowth),
        "Precise" => Ok(SpecialRule::Precise),
        "PrecisionDebuff" => Ok(SpecialRule::PrecisionDebuff),
        "PredatorFighter" => Ok(SpecialRule::PredatorFighter),
        "RapidCharge" => Ok(SpecialRule::RapidCharge),
        "RegenerativeStrength" => Ok(SpecialRule::RegenerativeStrength),
        "Resistance" => Ok(SpecialRule::Resistance),
        "SelfDestruct" => Ok(SpecialRule::SelfDestruct(0)), // Default value
        "Shred" => Ok(SpecialRule::Shred),
        "SpellConduit" => Ok(SpecialRule::SpellConduit),
        "StealthBuff" => Ok(SpecialRule::StealthBuff),
        "Strafing" => Ok(SpecialRule::Strafing),
        "TakedownStrike" => Ok(SpecialRule::TakedownStrike),
        "Unpredictable" => Ok(SpecialRule::Unpredictable),
        "UnpredictableFighter" => Ok(SpecialRule::UnpredictableFighter),
        "UnpredictableFighterMark" => Ok(SpecialRule::UnpredictableFighterMark),
        "Unique" => Ok(SpecialRule::Unique),
        "FuriousAura" => Ok(SpecialRule::FuriousAura),
        "HiveBondBoostAura" => Ok(SpecialRule::HiveBondBoostAura),
        "IncreasedShootingRangeAura" => Ok(SpecialRule::IncreasedShootingRangeAura),
        "RapidChargeAura" => Ok(SpecialRule::RapidChargeAura),
        "RegenerationAura" => Ok(SpecialRule::RegenerationAura),
        _ => Err(YamlError::InvalidSpecialRule(rule_str.to_string())),
    }
}

/// Extract a numeric parameter from a rule string like "AP(1)".
fn extract_parameter(rule_str: &str, prefix: &str) -> Option<u8> {
    if !rule_str.starts_with(prefix) {
        return None;
    }

    let rest = rule_str.strip_prefix(prefix)?;
    let rest = rest.trim_start_matches('(').trim_end_matches(')');
    rest.parse().ok()
}

/// Determine the selection mode based on the category name.
fn determine_selection_mode(category: &str) -> SelectionMode {
    if category.contains("Replace") || category.contains("Upgrade with one") {
        SelectionMode::PickOne
    } else {
        SelectionMode::Multiple
    }
}

/// Parse a cost modifier string like "+5pts" or "Free" into a numeric value.
///
/// # Errors
///
/// Returns an error if the format is invalid.
fn parse_cost_modifier(cost_str: &str) -> Result<u16, YamlError> {
    // Handle "Free" as 0 cost
    if cost_str == "Free" {
        return Ok(0);
    }

    let trimmed = cost_str
        .trim_start_matches('+')
        .trim_start_matches('-')
        .trim_end_matches("pts");
    trimmed
        .parse()
        .map_err(|_| YamlError::InvalidCostModifier(cost_str.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_quality() {
        assert_eq!(parse_quality("3+").unwrap(), 3);
        assert_eq!(parse_quality("4+").unwrap(), 4);
        assert_eq!(parse_quality("2+").unwrap(), 2);
    }

    #[test]
    fn test_parse_attacks() {
        assert_eq!(parse_attacks("A4").unwrap(), 4);
        assert_eq!(parse_attacks("A1").unwrap(), 1);
        assert_eq!(parse_attacks("A6").unwrap(), 6);
    }

    #[test]
    fn test_parse_special_rule() {
        assert_eq!(parse_special_rule("AP(1)").unwrap(), SpecialRule::AP(1));
        assert_eq!(
            parse_special_rule("Blast(3)").unwrap(),
            SpecialRule::Blast(3)
        );
        assert_eq!(
            parse_special_rule("Fearless").unwrap(),
            SpecialRule::Fearless
        );
        assert_eq!(parse_special_rule("Hero").unwrap(), SpecialRule::Hero);
    }
}
