//! Combat resolution calculator.
//!
//! Resolves an attack from an attacker unit against a defender unit,
//! applying special rules at the appropriate phases of the combat sequence.
//!
//! ## Combat Sequence & Rule Hook Points
//! 1. Attack count          - Impact(X)
//! 2. Hit roll setup        - Reliable, Artillery, Indirect, Thrust, Stealth
//! 3. Hit roll resolution   - Furious, Relentless, Surge, Rending
//! 4. Hit multiplication    - Blast(X)
//! 5. Defense roll setup    - AP(X)
//! 6. Defense roll resolve  - Bane, Unstoppable
//! 7. Wound application     - Deadly(X), Tough(X)
//! 8. Regeneration          - Regeneration (skipped by Bane/Rending/Unstoppable)

use crate::combat::context::CombatContext;
use crate::combat::dice;
use crate::models::rules::SpecialRule;
use crate::models::unit::Unit;
use crate::models::weapons::Weapon;

/// Detailed breakdown of a single attack resolution.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct AttackResult {
    /// Name of the weapon that made the attack
    pub weapon_name: String,
    /// Base number of attacks rolled
    pub base_attacks: u32,
    /// Extra attacks generated by special rules (Furious, Surge, etc.)
    pub extra_attacks: u32,
    /// Hits scored before multiplication
    pub hits_before_multiplier: u32,
    /// Hits after Blast multiplication
    pub total_hits: u32,
    /// Hits blocked by the defender
    pub blocked_hits: u32,
    /// Wounds actually inflicted (after Deadly/Tough)
    pub wounds_inflicted: u32,
    /// Wounds ignored by Regeneration
    pub regenerated_wounds: u32,
    /// Net wounds after regeneration
    pub net_wounds: u32,
}

/// Overall result of resolving an attacker against a defender.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct CombatResult {
    /// Per-weapon breakdowns
    pub attacks: Vec<AttackResult>,
    /// Total net wounds dealt to the defender
    pub total_net_wounds: u32,
    /// Total models removed from the defender
    pub models_removed: u32,
}

/// Resolve the attacks of `attacker` against `defender` under the given
/// combat context. This is the top-level entry point for the calculator.
///
/// # Errors
/// Returns an error string if the attack configuration is invalid.
pub fn resolve_attack(
    attacker: &Unit,
    defender: &Unit,
    context: &CombatContext,
) -> Result<CombatResult, String> {
    let mut result = CombatResult::default();

    let weapons: Vec<&Weapon> = select_weapons(attacker, context);

    // Phase 1: Impact(X) — extra dice on a charge unless fatigued
    if context.is_melee()
        && context.is_charging
        && !context.attacker_fatigued
        && let Some(impact) = resolve_impact(attacker, defender)
    {
        result.total_net_wounds = result.total_net_wounds.saturating_add(impact.net_wounds);
        result.attacks.push(impact);
    }

    for weapon in weapons {
        let attack = resolve_weapon_attack(attacker, weapon, defender, context)?;
        result.total_net_wounds = result.total_net_wounds.saturating_add(attack.net_wounds);
        result.attacks.push(attack);
    }

    result.models_removed = compute_models_removed(defender, result.total_net_wounds);

    Ok(result)
}

/// Resolve a single weapon's attacks against the defender.
///
/// The `Result` is retained for API symmetry with [`resolve_attack`]; future
/// rule validation (e.g. Impact resolution) may introduce error paths.
#[allow(clippy::unnecessary_wraps)]
fn resolve_weapon_attack(
    attacker: &Unit,
    weapon: &Weapon,
    defender: &Unit,
    context: &CombatContext,
) -> Result<AttackResult, String> {
    let mut attack = AttackResult {
        weapon_name: weapon.name.clone(),
        base_attacks: u32::from(weapon.total_attacks()),
        ..AttackResult::default()
    };

    // Phase 1: Attack count (Impact(X) would add dice here on a charge)
    // TODO: Resolve Impact(X)

    // Phase 2: Hit roll setup (modify Quality target)
    let hit_modifier = compute_hit_modifier(attacker, context);
    let quality_target = effective_quality(weapon, attacker, context);

    // Phase 3: Hit roll resolution
    let hit_rolls = dice::roll_d6s(attack.base_attacks, hit_modifier);
    let mut hits = dice::count_successes(&hit_rolls, quality_target);

    // Extra hits from Furious/Surge/Relentless on unmodified 6s
    // (checked on both the weapon and the unit, since upgrades like
    // Combat Bio-Engineer grant Furious at unit level)
    let extra_hits = count_extra_hits(&hit_rolls, weapon, attacker, context);
    attack.extra_attacks = extra_hits;
    hits = hits.saturating_add(extra_hits);
    attack.hits_before_multiplier = hits;

    // Rending: hits scored on unmodified 6s (original hits only — extras
    // don't count as 6s) block at AP(+4). Split before Blast so copies
    // of a rending hit keep the property.
    let six_count: u32 = hit_rolls
        .iter()
        .filter(|r| r.is_unmodified_six())
        .count()
        .try_into()
        .unwrap_or(u32::MAX);
    let rending_hits = if weapon.special_rules.contains(&SpecialRule::Rending) {
        six_count.min(hits)
    } else {
        0
    };
    let normal_hits = hits.saturating_sub(rending_hits);

    // Phase 4: Blast(X) hit multiplication (uniform across both pools)
    let rending_total = apply_blast(rending_hits, weapon, defender.quantity);
    let normal_total = apply_blast(normal_hits, weapon, defender.quantity);
    let total_hits = rending_total.saturating_add(normal_total);
    attack.total_hits = total_hits;

    // Phase 5: Defense roll setup (AP modifies the defense target)
    let defense_target = effective_defense(weapon, defender, context);

    // Phase 6: Defense roll resolution (Bane rerolls 6s, Rending +4 pool,
    // Shred extra wounds on 1s)
    let (blocked, shred_wounds) = roll_defense(rending_total, normal_total, defense_target, weapon);
    attack.blocked_hits = blocked;

    let failed_blocks = total_hits.saturating_sub(blocked);

    // Phase 7: Wound application (Deadly(X) multiplies wounds; Shred adds)
    let wounds = apply_deadly(failed_blocks, weapon).saturating_add(shred_wounds);
    attack.wounds_inflicted = wounds;

    // Phase 8: Regeneration (skipped if weapon ignores regen)
    let (net_wounds, regenerated) = apply_regeneration(wounds, defender, &weapon.special_rules);
    attack.regenerated_wounds = regenerated;
    attack.net_wounds = net_wounds;

    Ok(attack)
}

/// Weapons the attacker can use in this context.
///
/// Versatile Attack lets the unit choose any of its weapons whether
/// striking in melee or shooting; everyone else is limited to weapons
/// matching the context type.
#[must_use]
fn select_weapons<'a>(attacker: &'a Unit, context: &CombatContext) -> Vec<&'a Weapon> {
    if attacker.has_rule(&SpecialRule::VersatileAttack) {
        attacker.weapons.iter().collect()
    } else if context.is_melee() {
        attacker.melee_weapons()
    } else {
        attacker.ranged_weapons()
    }
}

/// Compute the total modifier to apply to hit rolls.
///
/// Battleborn: +1 to hit rolls when attacking in melee.
fn compute_hit_modifier(attacker: &Unit, context: &CombatContext) -> i32 {
    // Indirect (shooting after moving), Thrust (charging) and Stealth
    // (defender at >9") would add further modifiers here.
    // TODO: Implement those rule modifiers.
    if context.is_melee() && attacker.has_rule(&SpecialRule::Battleborn) {
        return 1;
    }
    0
}

/// Determine the effective Quality target for hit rolls.
/// Reliable forces Quality 2+.
fn effective_quality(weapon: &Weapon, attacker: &Unit, context: &CombatContext) -> u8 {
    // Fatigued units only hit on unmodified 6
    if context.attacker_fatigued {
        return 6;
    }

    // Reliable: this weapon attacks at Quality 2+
    if weapon.special_rules.contains(&SpecialRule::Reliable) {
        return 2;
    }

    attacker.quality
}

/// Count extra hits generated by Furious/Surge/Relentless on unmodified 6s.
/// Rules are checked on both the weapon and the attacking unit, since
/// upgrades can grant these rules at either level.
fn count_extra_hits(
    hit_rolls: &[dice::DieRoll],
    weapon: &Weapon,
    attacker: &Unit,
    context: &CombatContext,
) -> u32 {
    let sixes = hit_rolls.iter().filter(|r| r.is_unmodified_six()).count();

    let generates_extras = weapon
        .special_rules
        .iter()
        .chain(attacker.special_rules.iter())
        .any(|rule| rule_is_active_extra_hit(rule, context));

    if generates_extras {
        sixes.try_into().unwrap_or(u32::MAX)
    } else {
        0
    }
}

/// Whether an extra-hit-on-six rule is active given the combat context.
fn rule_is_active_extra_hit(rule: &SpecialRule, context: &CombatContext) -> bool {
    match rule {
        // Furious only triggers when charging in melee
        SpecialRule::Furious => context.is_charging && context.is_melee(),
        // Relentless only triggers at long range (ranged)
        SpecialRule::Relentless => context.is_ranged() && context.is_long_range(),
        // Surge triggers on any unmodified 6
        SpecialRule::Surge => true,
        _ => false,
    }
}

/// Apply Blast(X) multiplication, capped by the defender's model count.
fn apply_blast(hits: u32, weapon: &Weapon, defender_quantity: u8) -> u32 {
    let multiplier = weapon
        .special_rules
        .iter()
        .find_map(SpecialRule::blast_multiplier);

    match multiplier {
        Some(m) if m > 1 => {
            // Each hit is multiplied by X, but total capped by models in target
            let per_hit_cap = u32::from(m);
            let capped_multiplier = per_hit_cap.min(u32::from(defender_quantity));
            hits.saturating_mul(capped_multiplier)
        }
        _ => hits,
    }
}

/// Determine the effective Defense target, applying AP and cover.
fn effective_defense(weapon: &Weapon, defender: &Unit, context: &CombatContext) -> u8 {
    let mut defense = i32::from(defender.defense);

    // Cover: +1 to the defender's rolls vs shooting, so the defender
    // needs 1 LESS to block. (AP by contrast subtracts from the rolls,
    // so the target goes UP.)
    if context.is_ranged() && context.defender_in_cover {
        defense = defense.saturating_sub(1);
    }

    // Shielded: +1 to the defender's rolls in any context, so the
    // defender needs 1 LESS to block.
    if defender.has_rule(&SpecialRule::Shielded) {
        defense = defense.saturating_sub(1);
    }

    // AP(X): Target needs X higher to defend
    if let Some(ap) = weapon.get_ap() {
        defense = defense.saturating_add(i32::from(ap));
    }

    // Rending: unmodified 6 to hit gains AP(+4) — handled per-hit, placeholder
    // TODO: integrate Rending AP boost into the defense rolls for those hits

    // Clamp to valid range 2..=6 (a roll of 6 always succeeds regardless)
    defense.clamp(2, 6).try_into().unwrap_or(6)
}

/// Apply Deadly(X) wound multiplication.
fn apply_deadly(failed_blocks: u32, weapon: &Weapon) -> u32 {
    let multiplier = weapon
        .special_rules
        .iter()
        .find_map(SpecialRule::deadly_multiplier);

    match multiplier {
        Some(m) if m > 1 => failed_blocks.saturating_mul(u32::from(m)),
        _ => failed_blocks,
    }
}

/// Roll defense for the two hit pools and return `(blocked, shred_wounds)`.
/// The rending pool blocks at defense+4 (cap 6); Bane rerolls unmodified
/// defense 6s once; Shred adds one extra wound per unmodified 1 to block.
fn roll_defense(
    rending_hits: u32,
    normal_hits: u32,
    defense_target: u8,
    weapon: &Weapon,
) -> (u32, u32) {
    let has_bane = weapon.special_rules.contains(&SpecialRule::Bane);
    let has_shred = weapon.special_rules.contains(&SpecialRule::Shred);

    let mut blocked = 0u32;
    let mut shred_wounds = 0u32;

    if rending_hits > 0 {
        let rending_target = defense_target.saturating_add(4).min(6);
        let mut rolls = dice::roll_d6s(rending_hits, 0);
        if has_bane {
            reroll_sixes(&mut rolls);
        }
        blocked = blocked.saturating_add(dice::count_successes(&rolls, rending_target));
        if has_shred {
            shred_wounds = shred_wounds.saturating_add(count_ones(&rolls));
        }
    }

    if normal_hits > 0 {
        let mut rolls = dice::roll_d6s(normal_hits, 0);
        if has_bane {
            reroll_sixes(&mut rolls);
        }
        blocked = blocked.saturating_add(dice::count_successes(&rolls, defense_target));
        if has_shred {
            shred_wounds = shred_wounds.saturating_add(count_ones(&rolls));
        }
    }

    (blocked, shred_wounds)
}

/// Bane: reroll unmodified defense 6s once; the new result stands.
fn reroll_sixes(rolls: &mut [dice::DieRoll]) {
    for roll in rolls.iter_mut().filter(|r| r.raw == 6) {
        *roll = dice::roll_d6(0);
    }
}

/// Count unmodified 1s (used by Shred).
fn count_ones(rolls: &[dice::DieRoll]) -> u32 {
    rolls
        .iter()
        .filter(|r| r.is_unmodified_one())
        .count()
        .try_into()
        .unwrap_or(u32::MAX)
}

/// Apply defender Regeneration. Returns `(net_wounds, regenerated_count)`.
/// `weapon_rules` are the attacking weapon's rules; Bane/Rending/
/// Unstoppable skip regeneration entirely.
fn apply_regeneration(wounds: u32, defender: &Unit, weapon_rules: &[SpecialRule]) -> (u32, u32) {
    // If the weapon ignores regeneration, skip entirely
    let ignores_regen = weapon_rules.iter().any(SpecialRule::ignores_regeneration);

    if ignores_regen || !defender.has_regeneration() {
        return (wounds, 0);
    }

    // Regeneration: 5+ to ignore each wound
    let regen_rolls = dice::roll_d6s(wounds, 0);
    let ignored = dice::count_successes(&regen_rolls, 5);
    let net = wounds.saturating_sub(ignored);
    (net, ignored)
}

/// Resolve Impact(X): on a charge, roll X dice per model; each 2+ is a hit.
/// Impact hits have no AP/Deadly, are blocked at the defender's normal
/// defense value, and are subject to the defender's Regeneration.
fn resolve_impact(attacker: &Unit, defender: &Unit) -> Option<AttackResult> {
    let x = attacker
        .special_rules
        .iter()
        .find_map(SpecialRule::impact_dice)?;
    let dice_count = u32::from(x).saturating_mul(u32::from(attacker.quantity));
    let rolls = dice::roll_d6s(dice_count, 0);
    let hits = dice::count_successes(&rolls, 2);
    let defense_target = defender.defense.clamp(2, 6);
    let defense_rolls = dice::roll_d6s(hits, 0);
    let blocked = dice::count_successes(&defense_rolls, defense_target);
    let wounds = hits.saturating_sub(blocked);
    let (net_wounds, regenerated) = apply_regeneration(wounds, defender, &[]);
    Some(AttackResult {
        weapon_name: "Impact".to_string(),
        base_attacks: dice_count,
        hits_before_multiplier: hits,
        total_hits: hits,
        blocked_hits: blocked,
        wounds_inflicted: wounds,
        regenerated_wounds: regenerated,
        net_wounds,
        ..AttackResult::default()
    })
}

/// Compute how many models are removed given net wounds and tough values.
fn compute_models_removed(defender: &Unit, net_wounds: u32) -> u32 {
    let tough = defender.effective_tough();
    if tough == 0 {
        return 0;
    }
    net_wounds.checked_div(u32::from(tough)).unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::combat::context::CombatContext;
    use crate::models::unit::Unit;
    use crate::models::weapons::Weapon;

    #[test]
    fn test_basic_ranged_attack_resolves() {
        let attacker = Unit::new("Shooter", 3, 3, 3).with_weapon(Weapon::ranged("Rifle", 3, 1, 24));
        let defender = Unit::new("Target", 5, 3, 4);

        let context = CombatContext::ranged(12);
        let result = resolve_attack(&attacker, &defender, &context);
        assert!(result.is_ok());
    }

    #[test]
    fn test_ap_lowers_defense() {
        let defender = Unit::new("Target", 5, 3, 3);
        let weapon = Weapon::ranged("Plasma", 1, 1, 24).with_rule(SpecialRule::AP(1));
        let context = CombatContext::ranged(12);

        let effective = effective_defense(&weapon, &defender, &context);
        // Base defense 3, AP(1) raises required roll to 4
        assert_eq!(effective, 4);
    }

    #[test]
    fn test_cover_lowers_defense_target() {
        // Cover gives +1 to the defender's rolls, i.e. they need 1 LESS.
        let defender = Unit::new("Target", 5, 3, 4);
        let weapon = Weapon::ranged("Rifle", 1, 1, 24);
        let context = CombatContext::ranged(12).with_cover(true);

        assert_eq!(effective_defense(&weapon, &defender, &context), 3);
    }

    #[test]
    fn test_cover_no_effect_on_melee() {
        let defender = Unit::new("Target", 5, 3, 4);
        let weapon = Weapon::melee("Claws", 1, 1);
        let mut context = CombatContext::melee_charge();
        context.defender_in_cover = true;

        assert_eq!(effective_defense(&weapon, &defender, &context), 4);
    }

    #[test]
    fn test_ap_and_cover_stack() {
        // Defense 4, in cover (-1), AP(2) (+2) => 5
        let defender = Unit::new("Target", 5, 3, 4);
        let weapon = Weapon::ranged("Plasma", 1, 1, 24).with_rule(SpecialRule::AP(2));
        let context = CombatContext::ranged(12).with_cover(true);

        assert_eq!(effective_defense(&weapon, &defender, &context), 5);
    }

    #[test]
    fn test_reliable_overrides_quality() {
        let attacker = Unit::new("Shooter", 1, 5, 3)
            .with_weapon(Weapon::ranged("Sniper", 1, 1, 36).with_rule(SpecialRule::Reliable));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::ranged(12);

        assert_eq!(effective_quality(weapon, &attacker, &context), 2);
    }

    #[test]
    fn test_fatigue_forces_sixes_and_beats_reliable() {
        let attacker = Unit::new("Shooter", 1, 3, 3)
            .with_weapon(Weapon::ranged("Sniper", 1, 1, 36).with_rule(SpecialRule::Reliable));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::ranged(12).with_fatigue(true);

        assert_eq!(effective_quality(weapon, &attacker, &context), 6);
    }

    fn six_rolls(n: usize) -> Vec<dice::DieRoll> {
        vec![
            dice::DieRoll {
                raw: 6,
                modified: 6
            };
            n
        ]
    }

    #[test]
    fn test_extra_hits_furious_charging() {
        let attacker = Unit::new("Charger", 1, 3, 3)
            .with_weapon(Weapon::melee("Claws", 1, 3).with_rule(SpecialRule::Furious));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::melee_charge();

        assert_eq!(
            count_extra_hits(&six_rolls(3), weapon, &attacker, &context),
            3
        );
    }

    #[test]
    fn test_extra_hits_furious_not_charging() {
        let attacker = Unit::new("Fighter", 1, 3, 3)
            .with_weapon(Weapon::melee("Claws", 1, 3).with_rule(SpecialRule::Furious));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::melee_return(false);

        assert_eq!(
            count_extra_hits(&six_rolls(3), weapon, &attacker, &context),
            0
        );
    }

    #[test]
    fn test_extra_hits_relentless_long_range_only() {
        let attacker = Unit::new("Shooter", 1, 3, 3)
            .with_weapon(Weapon::ranged("Rifle", 1, 3, 24).with_rule(SpecialRule::Relentless));
        let weapon = attacker.weapons.first().expect("weapon present");

        let long = CombatContext::ranged(12);
        assert_eq!(count_extra_hits(&six_rolls(2), weapon, &attacker, &long), 2);

        let short = CombatContext::ranged(9);
        assert_eq!(
            count_extra_hits(&six_rolls(2), weapon, &attacker, &short),
            0
        );
    }

    #[test]
    fn test_extra_hits_surge_any_context() {
        let attacker = Unit::new("Shooter", 1, 3, 3)
            .with_weapon(Weapon::ranged("Rifle", 1, 3, 24).with_rule(SpecialRule::Surge));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::ranged(6);

        assert_eq!(
            count_extra_hits(&six_rolls(1), weapon, &attacker, &context),
            1
        );
    }

    #[test]
    fn test_extra_hits_unit_level_rule() {
        // Furious granted to the unit (not the weapon) still triggers.
        let attacker = Unit::new("Charger", 1, 3, 3)
            .with_rule(SpecialRule::Furious)
            .with_weapon(Weapon::melee("Claws", 1, 3));
        let weapon = attacker.weapons.first().expect("weapon present");
        let context = CombatContext::melee_charge();

        assert_eq!(
            count_extra_hits(&six_rolls(2), weapon, &attacker, &context),
            2
        );
    }

    #[test]
    fn test_blast_capped_by_models() {
        let weapon = Weapon::ranged("Launcher", 1, 2, 24).with_rule(SpecialRule::Blast(5));
        // 3 hits, Blast(5) capped by 2 models => 6
        assert_eq!(apply_blast(3, &weapon, 2), 6);
        // No Blast => unchanged
        let plain = Weapon::ranged("Rifle", 1, 2, 24);
        assert_eq!(apply_blast(3, &plain, 2), 3);
    }

    #[test]
    fn test_deadly_no_rule_passthrough() {
        let weapon = Weapon::melee("Claws", 1, 1);
        assert_eq!(apply_deadly(3, &weapon), 3);
    }

    #[test]
    fn test_regeneration_skipped_by_regen_ignoring_rules() {
        let defender = Unit::new("Target", 1, 3, 3).with_rule(SpecialRule::Regeneration);
        for rule in [
            SpecialRule::Bane,
            SpecialRule::Rending,
            SpecialRule::Unstoppable,
        ] {
            let (net, regenerated) = apply_regeneration(5, &defender, &[rule]);
            assert_eq!(net, 5);
            assert_eq!(regenerated, 0);
        }
    }

    #[test]
    fn test_regeneration_not_applied_without_rule() {
        let defender = Unit::new("Target", 1, 3, 3);
        let (net, regenerated) = apply_regeneration(5, &defender, &[]);
        assert_eq!(net, 5);
        assert_eq!(regenerated, 0);
    }

    #[test]
    fn test_impact_resolved_on_charge_only() {
        let attacker = Unit::new("Charger", 3, 3, 3)
            .with_rule(SpecialRule::Impact(3))
            .with_weapon(Weapon::melee("Claws", 3, 1));
        let defender = Unit::new("Target", 5, 3, 4);

        let charge = resolve_attack(&attacker, &defender, &CombatContext::melee_charge())
            .expect("resolution succeeds");
        let impact = charge.attacks.iter().find(|a| a.weapon_name == "Impact");
        let impact = impact.expect("Impact attack present on charge");
        assert_eq!(impact.base_attacks, 9); // 3 dice x 3 models

        let no_charge = resolve_attack(&attacker, &defender, &CombatContext::melee_return(false))
            .expect("resolution succeeds");
        assert!(no_charge.attacks.iter().all(|a| a.weapon_name != "Impact"));
    }

    #[test]
    fn test_tough_reduces_models_removed() {
        // Tough(3) needs 3 wounds per model removed; models_removed is
        // computed against the defender's tough, so the rule goes there.
        let attacker = Unit::new("Attacker", 3, 5, 5).with_weapon(Weapon::melee("Claws", 3, 1));
        let defender = Unit::new("Tough", 5, 3, 4).with_rule(SpecialRule::Tough(3));
        let charge = resolve_attack(&attacker, &defender, &CombatContext::melee_charge())
            .expect("resolution succeeds");
        // models_removed must equal floor(net / tough)
        let expected = charge.total_net_wounds / 3;
        assert_eq!(charge.models_removed, expected);
    }

    #[test]
    fn test_blast_multiplies_hits() {
        let weapon = Weapon::ranged("Launcher", 1, 2, 24).with_rule(SpecialRule::Blast(3));
        // Defender has 2 models, so multiplier capped at 2
        let total = apply_blast(2, &weapon, 2);
        assert_eq!(total, 4);
    }

    #[test]
    fn test_deadly_multiplies_wounds() {
        let weapon = Weapon::melee("Claws", 1, 1).with_rule(SpecialRule::Deadly(2));
        assert_eq!(apply_deadly(3, &weapon), 6);
    }

    #[test]
    fn test_unit_level_furious_generates_extra_hits_on_charge() {
        // Furious granted at unit level (e.g. via Combat Bio-Engineer upgrade)
        // must generate extra hits on unmodified 6s during a melee charge.
        let attacker = Unit::new("Charger", 5, 3, 3)
            .with_rule(SpecialRule::Furious)
            .with_weapon(Weapon::melee("Claws", 5, 2));
        let defender = Unit::new("Target", 5, 3, 4);

        let context = CombatContext::melee_charge();

        // Over 200 resolutions of 10 attacks, the chance of never rolling a
        // single 6 is negligible (~0.997^2000), so extras must appear.
        let mut saw_extras = false;
        for _ in 0..200 {
            let result =
                resolve_attack(&attacker, &defender, &context).expect("resolution succeeds");
            let attack = result.attacks.first().expect("one weapon");
            if attack.extra_attacks > 0 {
                saw_extras = true;
                break;
            }
        }
        assert!(
            saw_extras,
            "unit-level Furious should generate extra hits on unmodified 6s when charging"
        );
    }

    #[test]
    fn test_furious_does_not_trigger_on_ranged() {
        // Furious is melee-charge only; ranged attacks must never gain extras.
        let attacker = Unit::new("Shooter", 5, 3, 3)
            .with_rule(SpecialRule::Furious)
            .with_weapon(Weapon::ranged("Gun", 5, 2, 12));
        let defender = Unit::new("Target", 5, 3, 4);

        let context = CombatContext::ranged(12);
        for _ in 0..100 {
            let result =
                resolve_attack(&attacker, &defender, &context).expect("resolution succeeds");
            let attack = result.attacks.first().expect("one weapon");
            assert_eq!(attack.extra_attacks, 0);
        }
    }

    // ------------------------------------------------------------------
    // Battle Brothers rule effects
    // ------------------------------------------------------------------

    #[test]
    fn battleborn_grants_melee_hit_bonus_only() {
        let plain = Unit::new("Soldier", 1, 3, 3);
        let born = Unit::new("Soldier", 1, 3, 3).with_rule(SpecialRule::Battleborn);

        let melee = CombatContext::melee_charge();
        assert_eq!(compute_hit_modifier(&plain, &melee), 0);
        assert_eq!(compute_hit_modifier(&born, &melee), 1);

        // The bonus is melee-only.
        let ranged = CombatContext::ranged(12);
        assert_eq!(compute_hit_modifier(&born, &ranged), 0);
    }

    #[test]
    fn battleborn_hits_significantly_more_at_high_quality() {
        // Quality 6 needs natural 6s to hit; Battleborn's +1 turns 5s
        // into hits too. Over 600 single-attack resolutions the totals
        // diverge far beyond any flaking: E[plain] = 600/6 = 100,
        // E[Born] = 600/3 = 200, sigma ~9-12.
        let resolve_hits = |with_born: bool| -> u32 {
            let mut unit = Unit::new("Q6", 1, 6, 3).with_weapon(Weapon::melee("Claws", 1, 1));
            if with_born {
                unit = unit.with_rule(SpecialRule::Battleborn);
            }
            let defender = Unit::new("Target", 5, 3, 4);
            let mut hits = 0u32;
            for _ in 0..600 {
                let result = resolve_attack(&unit, &defender, &CombatContext::melee_charge())
                    .expect("resolution succeeds");
                hits += result
                    .attacks
                    .first()
                    .expect("one weapon")
                    .hits_before_multiplier;
            }
            hits
        };

        let plain = resolve_hits(false);
        let born = resolve_hits(true);
        assert!(
            born > plain,
            "Battleborn (total {born}) must hit more than plain (total {plain})"
        );
        // 6-sigma bands around the expectations 100 / 200.
        assert!(
            (40..=160).contains(&plain),
            "plain Q6 total {plain} far off 100"
        );
        assert!(
            (140..=260).contains(&born),
            "Battleborn Q6 total {born} far off 200"
        );
    }

    #[test]
    fn versatile_attack_offers_every_weapon_in_any_context() {
        let plain = Unit::new("Fighter", 1, 3, 3)
            .with_weapon(Weapon::melee("Claws", 1, 2))
            .with_weapon(Weapon::ranged("Pistol", 1, 1, 18));
        let versatile = plain.clone().with_rule(SpecialRule::VersatileAttack);

        let melee = CombatContext::melee_charge();
        let ranged = CombatContext::ranged(3);

        // Without the rule, contexts only offer weapons of the matching
        // type (previous behavior).
        assert_eq!(select_weapons(&plain, &melee).len(), 1);
        assert_eq!(select_weapons(&plain, &ranged).len(), 1);

        // Versatile Attack unlocks every weapon in every context.
        assert_eq!(select_weapons(&versatile, &melee).len(), 2);
        assert_eq!(select_weapons(&versatile, &ranged).len(), 2);
    }

    #[test]
    fn versatile_attacker_resolves_melee_with_all_weapons() {
        let attacker = Unit::new("Fighter", 1, 3, 3)
            .with_weapon(Weapon::melee("Claws", 1, 2))
            .with_weapon(Weapon::ranged("Pistol", 1, 1, 18))
            .with_rule(SpecialRule::VersatileAttack);
        let defender = Unit::new("Target", 5, 3, 4);

        let result = resolve_attack(&attacker, &defender, &CombatContext::melee_charge())
            .expect("resolution succeeds");
        let names: Vec<&str> = result
            .attacks
            .iter()
            .map(|a| a.weapon_name.as_str())
            .collect();
        assert!(
            names.contains(&"Claws") && names.contains(&"Pistol"),
            "Versatile Attack must resolve every weapon, got {names:?}"
        );
    }

    #[test]
    fn shielded_lowers_defense_target_in_any_context() {
        let plain = Unit::new("Guard", 1, 3, 3);
        let shielded = Unit::new("Guard", 1, 3, 3).with_rule(SpecialRule::Shielded);

        let melee_weapon = Weapon::melee("Claws", 1, 2);
        let melee = CombatContext::melee_charge();
        assert_eq!(effective_defense(&melee_weapon, &plain, &melee), 3);
        assert_eq!(effective_defense(&melee_weapon, &shielded, &melee), 2);

        let ranged_weapon = Weapon::ranged("Rifle", 1, 1, 24);
        let ranged = CombatContext::ranged(12);
        assert_eq!(effective_defense(&ranged_weapon, &plain, &ranged), 3);
        assert_eq!(effective_defense(&ranged_weapon, &shielded, &ranged), 2);

        // Stacks with cover but clamps at the 2..=6 roll range.
        assert_eq!(
            effective_defense(&ranged_weapon, &shielded, &ranged.with_cover(true)),
            2
        );
    }
}
